spring.application.name=co

# H2 Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console Settings
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
# Fix for "Refused to display in a frame" error in browser
#spring.h2.console.settings.web-allow-others=true

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=create-drop
# Useful for debugging your "a_" column mappings
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=76CUJu0d5V6sPia26P7Zj6145iW1In7NyI6DJTCGFD8=
jwt.expiration=60000